import type { CommercialState } from "./types";
import { defaultDiscounts, defaultPrograms, defaultRolePermissions } from "./admin-config";

export const seedState: CommercialState = {
  month: "Junio 2026",
  companyGoal: 120000,
  avgResponseTime: "07m 42s",
  teams: [
    { id: "team-azul", name: "Equipo Azul", color: "#00A7EB", leaderId: "exec-1", goalAmount: 42000, active: true },
    { id: "team-guinda", name: "Equipo Guinda", color: "#7B1238", leaderId: "exec-2", goalAmount: 38000, active: true },
    { id: "team-verde", name: "Equipo Verde", color: "#34C759", leaderId: "exec-3", goalAmount: 40000, active: true }
  ],
  executives: [
    {
      id: "exec-1",
      fullName: "Eliana Benavides",
      code: "E-019",
      teamId: "team-azul",
      shift: "Manana",
      status: "Activo",
      goalAmount: 28000,
      currentSales: 32400,
      points: 245,
      previousRank: 3
    },
    {
      id: "exec-2",
      fullName: "Anarosa Bustamante",
      code: "E-086",
      teamId: "team-guinda",
      shift: "Tarde",
      status: "Activo",
      goalAmount: 24000,
      currentSales: 28750,
      points: 221,
      previousRank: 1
    },
    {
      id: "exec-3",
      fullName: "Mariana Haro",
      code: "E-044",
      teamId: "team-verde",
      shift: "Manana",
      status: "Activo",
      goalAmount: 23000,
      currentSales: 13350,
      points: 134,
      previousRank: 4
    }
  ],
  sales: [
    {
      id: "sale-1",
      saleDate: "2026-06-10",
      executiveId: "exec-1",
      teamId: "team-azul",
      productType: "Diplomado",
      productName: "Diplomado en Salud Ocupacional",
      quantity: 6,
      grossAmount: 18000,
      discountAmount: 900,
      netAmount: 17100,
      leadSource: "WhatsApp",
      paymentMethod: "Transferencia",
      validationStatus: "validada"
    },
    {
      id: "sale-2",
      saleDate: "2026-06-11",
      executiveId: "exec-2",
      teamId: "team-guinda",
      productType: "Curso Modular",
      productName: "Emergencias y Desastres",
      quantity: 8,
      grossAmount: 12800,
      discountAmount: 650,
      netAmount: 12150,
      leadSource: "Meta Ads",
      paymentMethod: "Yape",
      validationStatus: "validada"
    },
    {
      id: "sale-3",
      saleDate: "2026-06-11",
      executiveId: "exec-3",
      teamId: "team-verde",
      productType: "Curso",
      productName: "Inyectoterapia",
      quantity: 5,
      grossAmount: 4500,
      discountAmount: 200,
      netAmount: 4300,
      leadSource: "Base",
      paymentMethod: "Tarjeta",
      validationStatus: "pendiente_validacion"
    }
  ],
  users: [
    {
      id: "user-admin",
      fullName: "Administrador Comercial",
      email: "admin@test.com",
      role: "Superadministrador",
      area: "Gerencia Comercial",
      status: "Activo",
      lastAccess: "Hoy 09:42",
      createdAt: "2026-06-11",
      avatarUrl: "/avatars/gerencia.svg"
    }
  ],
  programs: defaultPrograms,
  discounts: defaultDiscounts,
  rolePermissions: defaultRolePermissions,
  audit: [
    {
      id: "audit-1",
      createdAt: "2026-06-11 10:42",
      actor: "Administrador Comercial",
      action: "Actualizo ranking",
      module: "Dashboard",
      target: "Junio 2026",
      result: "Exitoso",
      criticality: "Media",
      before: "Datos locales",
      after: "Indicadores sincronizados"
    }
  ],
  clientProfiles: [
    {
      id: "medicos",
      name: "Medicos",
      description: "Profesionales que buscan actualizacion continua, respaldo institucional y recertificacion.",
      pain: "Necesitan mantenerse actualizados y cumplir requisitos de recertificacion.",
      motivator: "Certificaciones, horas academicas, respaldo institucional y mejora curricular.",
      frequency: "Capacitacion continua anual",
      loyalty: "Alta",
      urgency: "Alta",
      priceSensitivity: "Media",
      modality: "Virtual / Semipresencial",
      status: "Activo",
      pains: ["Recertificacion", "Actualizacion de CV", "Cargos jefaturales"],
      motivators: ["Creditos academicos", "Certificaciones respaldadas", "Especializacion"],
      objections: ["Necesito validar horas", "Quiero respaldo institucional"],
      arguments: ["Fortalece su CV y su actualizacion profesional con certificacion respaldada."],
      programs: ["Salud Ocupacional", "Auditoria Medica", "Gestion en Salud"],
      messages: ["Doctor, este programa le ayuda a fortalecer su actualizacion profesional y sumar formacion util para su CV."]
    },
    {
      id: "enfermeria",
      name: "Licenciados en Enfermeria",
      description: "Buscan capacitacion practica, certificada y accesible para mejorar su perfil laboral.",
      pain: "Necesitan actualizar su CV y demostrar competencias practicas.",
      motivator: "Mejora laboral, registros profesionales y cursos aplicables.",
      frequency: "Una o dos veces al ano",
      loyalty: "Alta",
      urgency: "Alta",
      priceSensitivity: "Media",
      modality: "Flexible",
      status: "Activo",
      pains: ["Actualizacion de CV", "Mejora salarial", "Conocimientos practicos"],
      motivators: ["Ascensos", "Concursos", "Certificacion respaldada"],
      objections: ["Esta caro", "No tengo tiempo"],
      arguments: ["El programa esta disenado para fortalecer su desempeno con conocimientos practicos."],
      programs: ["Emergencias y Desastres", "Central de Esterilizacion", "UCI"],
      messages: ["Licenciada, este programa puede ayudarle a fortalecer su perfil profesional con conocimientos practicos aplicables."]
    },
    {
      id: "obstetras",
      name: "Obstetras",
      description: "Valoran flexibilidad, tecnicas actualizadas e independencia profesional.",
      pain: "Necesitan diferenciarse con tecnicas innovadoras y mejores oportunidades.",
      motivator: "Flexibilidad horaria, mejora remunerativa y consultorios particulares.",
      frequency: "Cada campana relevante",
      loyalty: "Media",
      urgency: "Media",
      priceSensitivity: "Media",
      modality: "Virtual",
      status: "Activo",
      pains: ["Primeras oportunidades", "Actualizacion tecnica", "Mejora remunerativa"],
      motivators: ["Independencia laboral", "Consejerias", "Flexibilidad"],
      objections: ["Quiero algo mas practico", "No se si me sirve para mi area"],
      arguments: ["Esta formacion refuerza habilidades aplicables para atencion y consejeria."],
      programs: ["Psicoprofilaxis", "Salud Materna", "Ecografia basica"],
      messages: ["Obstetra, este curso le ayuda a reforzar capacidades practicas para ampliar sus oportunidades."]
    },
    {
      id: "tecnicos",
      name: "Tecnicos en Enfermeria",
      description: "Buscan certificarse rapido, mejorar ingresos y aprender procedimientos practicos.",
      pain: "Quieren escalar a trabajos con mejor remuneracion.",
      motivator: "Costos economicos, certificados en menor tiempo y practica directa.",
      frequency: "Por oportunidad laboral",
      loyalty: "Media",
      urgency: "Critica",
      priceSensitivity: "Alta",
      modality: "Flexible",
      status: "Activo",
      pains: ["Mejor remuneracion", "Primer empleo", "Certificacion rapida"],
      motivators: ["Procedimientos practicos", "Ascenso laboral", "Costo accesible"],
      objections: ["Esta caro", "Necesito algo rapido"],
      arguments: ["Este curso fortalece habilidades practicas y mejora su perfil laboral en menos tiempo."],
      programs: ["Auxiliar de Enfermeria", "Inyectoterapia", "Toma de muestras"],
      messages: ["Este curso esta disenado para fortalecer sus habilidades practicas y mejorar su perfil laboral."]
    },
    {
      id: "general",
      name: "Publico en General",
      description: "Personas que desean aprender un oficio y generar ingresos.",
      pain: "Buscan una alternativa accesible para empezar sin examen inicial.",
      motivator: "Aprender un oficio, diploma en menor tiempo y costos economicos.",
      frequency: "Segun necesidad de ingreso",
      loyalty: "Media",
      urgency: "Alta",
      priceSensitivity: "Alta",
      modality: "Presencial / Flexible",
      status: "Activo",
      pains: ["Obtener ingresos", "Sin examen inicial", "Aprender rapido"],
      motivators: ["Oficio aplicable", "Diploma rapido", "Costo economico"],
      objections: ["No tengo experiencia", "Quiero algo facil de iniciar"],
      arguments: ["Puede aprender una habilidad aplicable sin examen inicial y con certificacion en menor tiempo."],
      programs: ["Cosmiatria", "Primeros auxilios", "Inyectoterapia"],
      messages: ["Este curso esta pensado para personas que desean aprender un oficio de manera accesible."]
    },
    {
      id: "extranjero",
      name: "Publico Extranjero",
      description: "Busca modalidad virtual, confianza institucional y mejor posicion laboral.",
      pain: "Necesitan estudiar desde otro pais con respaldo confiable.",
      motivator: "Modalidad virtual, accesibilidad economica y docentes variados.",
      frequency: "Flexible",
      loyalty: "Media",
      urgency: "Media",
      priceSensitivity: "Media",
      modality: "Virtual",
      status: "Activo",
      pains: ["Confianza institucional", "Modalidad virtual", "Mejores puestos"],
      motivators: ["Intercambio de conocimiento", "Acceso remoto", "Mejora de ingresos"],
      objections: ["No estoy en Peru", "Necesito clases virtuales"],
      arguments: ["La modalidad virtual le permite formarse desde su pais con una institucion posicionada."],
      programs: ["Gestion en Salud", "Salud Publica", "Emergencias"],
      messages: ["Puede capacitarse en modalidad virtual con respaldo institucional y acceso flexible."]
    }
  ]
};
